# Generated by Django 3.0.8 on 2020-07-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('local', 'Local Address'), ('permanent', 'Permanent Address')], default='permanent', max_length=512)),
                ('line1', models.CharField(blank=True, max_length=512)),
                ('line2', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, max_length=512)),
                ('taluka', models.CharField(blank=True, max_length=512)),
                ('dist', models.CharField(blank=True, max_length=512)),
                ('pin', models.CharField(blank=True, max_length=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('place', models.CharField(max_length=256)),
                ('academic_year', models.CharField(max_length=32)),
                ('max_standards', models.PositiveIntegerField()),
                ('max_staff', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=1, unique=True)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn', models.IntegerField(unique=True)),
                ('student_id', models.CharField(max_length=19)),
                ('uid', models.CharField(blank=True, max_length=12, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('cast', models.CharField(max_length=256)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('father_middle_name', models.CharField(blank=True, max_length=256, null=True)),
                ('nationality', models.CharField(blank=True, max_length=256, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student/%Y/%m/%d/')),
                ('last_school', models.CharField(blank=True, max_length=256, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ManyToManyField(blank=True, to='school.Address')),
                ('admitted_std', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Standard')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.CastCategory')),
                ('mother_tongue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Language')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Religion')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='school.Standard')),
            ],
        ),
    ]
